# Generated by Django 6.0 on 2025-12-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
